### ISSUE TITLE
Implement new mob skills

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#1525]
There are some new mob skills that are left unimplemented.

**Comment by Lemongrass3110** [comment]
#1893 is one of them

**Comment by Jeybla** [comment]
Can we make up a list of missing skills?
Or else the issue isn't really valuable.

**Comment by secretdataz** [comment]
```
//****
// New NPC Wide Status AoE Skills And Others
//700,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDEHEALTHFEAR,Wide Health Fear
//701,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDEBODYBURNNING,Wide Body Burnning
//702,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDEFROSTMISTY,Wide Freezing
//703,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDECOLD,Wide Crystalize
//704,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDE_DEEP_SLEEP,Wide Deep Sleep
//705,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDESIREN,Wide Siren's Voice
706,0,6,4,5,0,0,10,1,no,0,0x2,0,magic,0,0x1,	NPC_VENOMFOG,Venom Fog
//707,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_MILLENNIUMSHIELD,Millenium Shield 2
//708,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_COMET,Comet 2
//709,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_ICEMINE,Ice Mine
//710,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_ICEEXPLO,Ice Explosion
//711,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_FLAMECROSS,Flame Cross
//712,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_PULSESTRIKE2,Pulse Strike 2
//713,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_DANCINGBLADE,Dancing Blade
//714,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_DANCINGBLADE_ATK,Dancing Blade Attack
//715,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_DARKPIERCING,Dark Piercing
716,0,6,4,0,0x1,0,10,0,no,0,0x2,0,none,0,0x0,		NPC_MAXPAIN,Max Pain
717,0,6,1,0,0xD2,18,10,1,no,0,0x2,0,misc,0,0x0,		NPC_MAXPAIN_ATK,Max Pain Attack
//718,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_DEATHSUMMON,Death Summon
//719,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_HELLBURNING,Hell Burning
//720,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_JACKFROST,Jack Frost 2
//721,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDEWEB,Wide Web
//722,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDESUCK,Wide Suck
//723,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_STORMGUST2,Storm Gust 2
//724,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_FIRESTORM,Fire Storm
//725,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_REVERBERATION,Reverberation 2
//726,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_REVERBERATION_ATK,Reverberation Attack
//727,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_LEX_AETERNA,Lex Aeterna 2
//728,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_ARROWSTORM,NPC Arrow Storm
//729,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_CHEAL,NPC Coluceo Heal
//730,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_SR_CURSEDCIRCLE,NPC 
//731,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_DRAGONBREATH,NPC Dragon Breath
//732,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_FATALMENACE,NPC Fatal Menace
//733,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_MAGMA_ERUPTION,NPC Magma Eruption
//734,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_MAGMA_ERUPTION_DOTDAMAGE,NPC Magma Eruption Dot Damage
//735,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_MANDRAGORA,NPC Howling of Mandragora
//736,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_PSYCHIC_WAVE,NPC Psychic Wave
//737,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_RAYOFGENESIS,NPC Ray of Genesis
//738,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_VENOMIMPRESS,NPC Venom Impress
//739,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_CLOUD_KILL,NPC Cloud Kill
//740,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_IGNITIONBREAK,NPC Ignition Break
//741,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_PHANTOMTHRUST,NPC Phantom Thrust
//742,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_POISON_BUSTER,NPC Poison Blaster
//743,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_HALLUCINATIONWALK,NPC Hallucination Walk
//744,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_ELECTRICWALK,NPC Electric Walk
//745,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_FIREWALK,NPC Fire Walk
//746,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDEDISPEL,Wide Dispell
//747,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_LEASH,Leash
//748,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDELEASH,Wide Leash
//749,0,0,0,0,0,0,??,0,no,0,0,0,none,0,0x0,		NPC_WIDECRITICALWOUND,Wide Critical Wound
```

**Comment by aleos89** [comment]
[NPC_HELLBURNING](#5274)

**Comment by Lemongrass3110** [comment]
Updated the list:

- [ ] NPC_WIDEHEALTHFEAR
- [ ] NPC_WIDEBODYBURNNING
- [ ] NPC_WIDEFROSTMISTY
- [ ] NPC_WIDECOLD
- [ ] NPC_WIDE_DEEP_SLEEP
- [ ] NPC_WIDESIREN
- [X] NPC_VENOMFOG: #1889
- [X] NPC_MILLENNIUMSHIELD: #6343
- [X] NPC_COMET: #3041
- [X] NPC_ICEMINE: #2555
- [ ] NPC_ICEEXPLO
- [X] NPC_FLAMECROSS: #2555
- [X] NPC_PULSESTRIKE2: #6343
- [X] NPC_DANCINGBLADE: #6343
- [X] NPC_DANCINGBLADE_ATK: #6343
- [X] NPC_DARKPIERCING: #3228
- [X] NPC_MAXPAIN: #1813
- [X] NPC_MAXPAIN_ATK: #1813
- [X] NPC_DEATHSUMMON: #2775
- [X] NPC_HELLBURNING: #5274
- [X] NPC_JACKFROST: #3173
- [X] NPC_WIDEWEB: #5611
- [X] NPC_WIDESUCK: #5611
- [X] NPC_STORMGUST2: #6343
- [X] NPC_FIRESTORM: #5611
- [X] NPC_REVERBERATION: #4061
- [X] NPC_REVERBERATION_ATK: #4061
- [X] NPC_LEX_AETERNA: #3228
- [X] NPC_ARROWSTORM: #3228
- [X] NPC_CHEAL: #6343
- [X] NPC_SR_CURSEDCIRCLE: #6343
- [X] NPC_DRAGONBREATH: #6343
- [X] NPC_FATALMENACE: #6343
- [X] NPC_MAGMA_ERUPTION: #6343
- [X] NPC_MAGMA_ERUPTION_DOTDAMAGE: #6343
- [X] NPC_MANDRAGORA: #6343
- [X] NPC_PSYCHIC_WAVE: #6343
- [X] NPC_RAYOFGENESIS: #6343
- [X] NPC_VENOMIMPRESS: #6343
- [X] NPC_CLOUD_KILL: #3586
- [X] NPC_IGNITIONBREAK: #3586
- [X] NPC_PHANTOMTHRUST: #3586
- [X] NPC_POISON_BUSTER: #3586
- [X] NPC_HALLUCINATIONWALK: #3586
- [X] NPC_ELECTRICWALK: #3586
- [X] NPC_FIREWALK: #3586
- [ ] NPC_WIDEDISPEL
- [ ] NPC_LEASH
- [ ] NPC_WIDELEASH
- [ ] NPC_WIDECRITICALWOUND

**Comment by Atemo** [comment]
Another list (not including those from https://github.com/rathena/rathena/pull/7552)
```

	NPC_ACIDBREATH2,
	NPC_EVILLAND2,
	NPC_RAINOFMETEOR,
	NPC_GROUNDDRIVE,
	NPC_RELIEVE_ON,
	NPC_RELIEVE_OFF,
	NPC_LOCKON_LASER,
	NPC_LOCKON_LASER_ATK,
	NPC_SEEDTRAP,
	NPC_DEADLYCURSE,
	NPC_RANDOMBREAK,
	NPC_STRIP_SHADOW,
	NPC_DEADLYCURSE2,
	NPC_CANE_OF_EVIL_EYE,
	NPC_CURSE_OF_RED_CUBE,
	NPC_CURSE_OF_BLUE_CUBE,
	NPC_KILLING_AURA,	// 783
```

**Comment by OptimusM** [comment]
> Another list:
> 
> * [ ]  NPC_WIDEBLEEDING2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_WIDESILENCE2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_WIDESTUN2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_WIDESTONE2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_WIDESLEEP2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_WIDECURSE2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_WIDECONFUSE2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_WIDEFREEZE2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_BLEEDING2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_ICEBREATH2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_ACIDBREATH2
> * [ ]  NPC_EVILLAND2
> * [ ]  NPC_HELLJUDGEMENT2: [Implemented missing skills #7552](https://github.com/rathena/rathena/pull/7552)
> * [ ]  NPC_RAINOFMETEOR
> * [ ]  NPC_GROUNDDRIVE
> * [ ]  NPC_RELIEVE_ON
> * [ ]  NPC_RELIEVE_OFF
> * [ ]  NPC_LOCKON_LASER
> * [ ]  NPC_LOCKON_LASER_ATK
> * [ ]  NPC_SEEDTRAP
> * [ ]  NPC_DEADLYCURSE
> * [ ]  NPC_RANDOMBREAK
> * [ ]  NPC_STRIP_SHADOW
> * [ ]  NPC_DEADLYCURSE2
> * [ ]  NPC_CANE_OF_EVIL_EYE
> * [ ]  NPC_CURSE_OF_RED_CUBE
> * [ ]  NPC_CURSE_OF_BLUE_CUBE
> * [ ]  NPC_KILLING_AURA

I have done some research on these but, i can't find any information about 3 skills:
 NPC_SEEDTRAP
 NPC_CURSE_OF_RED_CUBE
 NPC_CURSE_OF_BLUE_CUBE
 
 Anyone has some information about those?

**Comment by ShiraGawaAnri** [comment]
NPC_SEEDTRAP
I saw this skill on the Japan RO server. Does this scenario work? Should I capture a video or just provide a direct link?
